In [1]:
import numpy as np


In [17]:
arr = np.zeros((2,3,4))
print(arr.dtype)
print(arr)

float64
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
b = np.array([
    [
        [1,2],
        [3,4]
    ],

    [
        [5,6],
        [7,8]
    ]
])